name: Sphinx build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python # Set Python version
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        cd docs
        pip install -r requirements.txt
        cd ..
    - uses: actions/checkout@v3
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      run: |
        cd docs
        make clean html
        make html
        cd ..
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html